server:
  port: 80


spring:  application:    name: cloud-order-service-openfeign-hystrix
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka, http://eureka7003.com:7003/eureka
     
  
logging:  level:    com.mguo.springcloud.service.FeignPaymentService: debug
    
ribbon: 
  ReadTimeout: 5000
  ConeectTimeout: 5000

feign:  hystrix:    enabled: true