server:
  port: 9004

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848 #配置Nacos地址
        server-addr: 192.168.0.102:1111

management:
  endpoints:
    web:
      exposure:
        include: '*'





